# -*- mode: python ; coding: utf-8 -*-
"""OPTIONAL single-file build. Most people should not use this.

Read ``DivineClient.spec`` first: onedir is the layout that stops getting quarantined.
This variant exists only for the case where a single ``DivineClient.exe`` genuinely
matters (a kiosk machine, a USB stick, a "one file, one double-click" handoff).

What you give up by choosing it:

* The bootloader unpacks ~40 MB into ``%TEMP%\\_MEIxxxxxx`` on every start, runs
  from there, and deletes it on exit. Defender's behaviour monitor watches exactly
  that pattern, which is why onefile PyInstaller apps get flagged far more often.
* Startup is a few seconds slower, and an interrupted first launch leaves junk in
  Temp.
* SmartScreen reputation is per-file-hash, and the hash changes on every rebuild
  with no way to cache it, so every release gets "unknown publisher" again.

Mitigations already applied here: no UPX, a real version resource, and the crash
reporter in ``main.py`` so a blocked start still leaves a log. If you ship this to
other people, sign it (``build_exe.bat -sign``) and consider an installer into
``Program Files`` instead - both help far more than packing ever does.

Build with:  python -m PyInstaller DivineClient.onefile.spec --noconfirm
Output:      dist\\DivineClient.exe
"""
import os
import re

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

APP_NAME = "DivineClient"
PROJECT_ROOT = os.path.abspath(os.path.dirname(SPEC))
ICON = os.path.join(PROJECT_ROOT, "assets", "icon.ico")

# Kept in sync with DivineClient.spec on purpose: a version resource is the single
# cheapest way to look like a real application instead of a mystery binary, and it
# matters *more* in a one-file build, where the exe is the only thing to inspect.
DEFAULT_VERSION = "0.0.0"


def _app_version():
    init = os.path.join(PROJECT_ROOT, "divineclient", "__init__.py")
    try:
        with open(init, "r", encoding="utf-8") as handle:
            match = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', handle.read())
        if match:
            return match.group(1).strip()
    except OSError:
        pass
    return DEFAULT_VERSION


def _numeric(version, parts=4):
    nums = [int(n) for n in re.findall(r"\d+", version or "")][:parts]
    while len(nums) < parts:
        nums.append(0)
    return tuple(nums)


def write_version_resource(version):
    nums = _numeric(version)
    text = """# UTF-8
# Generated by DivineClient.onefile.spec from divineclient.__version__ - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Divine Dev Team'),
            StringStruct('FileDescription', 'Divine Client - Minecraft launcher (single file)'),
            StringStruct('FileVersion', '{version}'),
            StringStruct('InternalName', 'DivineClient'),
            StringStruct('LegalCopyright', 'Copyright (C) Divine Dev Team'),
            StringStruct('OriginalFilename', 'DivineClient.exe'),
            StringStruct('ProductName', 'Divine Client'),
            StringStruct('ProductVersion', '{version}'),
            StringStruct('Comments', 'Open-source Minecraft launcher. https://divineclient.wispbyte.org')
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [0, 1200])])
  ]
)
""".format(nums=nums, version=version)
    out_dir = os.path.join(PROJECT_ROOT, "build")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "version_info_onefile.txt")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return path


VERSION_FILE = write_version_resource(_app_version())

# hero_bg.png left out on purpose (see DivineClient.spec): the Home page paints its own
# background, so that 2 MB is design art with no code path.
#: The images and files the launcher loads by name at runtime. The four ui_*.png marks and
#: the mono icon are globbed rather than listed: a hand-maintained tuple is exactly how
#: every icon added to assets/ quietly stopped shipping in the built exe (the UI falls back
#: to text, so nothing fails loudly - the icons are just gone for players and not for us).
# keep in step with DivineClient.spec, which explains why this list is globbed and tested
ASSET_FILES = ("emblem.png", "logo.png", "logo_stacked.png", "icon.ico",
               "hero_bg.png")
_ASSETS_DIR = os.path.join(PROJECT_ROOT, "assets")
if os.path.isdir(_ASSETS_DIR):
    ASSET_FILES += tuple(sorted(n for n in os.listdir(_ASSETS_DIR)
                                if n.startswith(("ui_", "icon_mono"))))
datas = [(os.path.join(PROJECT_ROOT, "assets", name), "assets")
         for name in ASSET_FILES
         if os.path.isfile(os.path.join(PROJECT_ROOT, "assets", name))]
datas += collect_data_files("customtkinter")
web_dir = os.path.join(PROJECT_ROOT, "divineclient", "web")
if os.path.isdir(web_dir):
    datas.append((web_dir, "divineclient/web"))

hiddenimports = ["PIL._tkinter_finder"]
hiddenimports += collect_submodules("minecraft_launcher_lib")
hiddenimports += collect_submodules("customtkinter")
hiddenimports += collect_submodules("pypresence")
hiddenimports += collect_submodules("divineclient")
hiddenimports += collect_submodules("flask")
hiddenimports += collect_submodules("webview")

excludes = [
    "numpy", "scipy", "pandas", "matplotlib",
    "PyQt5", "PyQt6", "PySide2", "PySide6",
    "IPython", "pytest", "test", "setuptools",
]

a = Analysis(
    [os.path.join(PROJECT_ROOT, "main.py")],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                       # see the module docstring: packing is the problem
    upx_exclude=[],
    runtime_tmpdir=None,             # left alone; a fixed temp dir does not help
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON if os.path.isfile(ICON) else None,
    version=VERSION_FILE,
    uac_admin=False,
    uac_uiaccess=False,
)
