# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build file for Divine Client - ONE-DIR layout (the default, and the one
to ship).

Why this file looks the way it does
----------------------------------
The previous build was `onefile` with `upx=True`. That combination is the classic
false-positive recipe, and it is the reason people reported "Divine Client is a
virus":

* **UPX** is a real packer. Packed code has to unpack itself in memory, so every
  heuristic engine treats "UPX stub + unknown app" as suspicious. Nothing about our
  exe is improved by it - it saves a few MB and buys a detection.
* **onefile** unpacks the whole program into ``%TEMP%\\_MEIxxxxxx`` on every start
  and runs Python from there. Dropping executables into a temp folder and executing
  them is what dropper malware does; it also makes Defender scan the payload on
  each launch instead of once.
* A PyInstaller exe with **no version resource** reports an empty Company/
  Product/FileDescription. An exe that lies about nothing but also says nothing
  looks far worse in a reputation engine than one that says "Divine Client,
  Divine Dev Team, 1.0.0".

So: onedir (a normal folder with the exe beside ``_internal\\``, no temp
extraction, no runtime self-write), ``upx=False``, and a generated version
resource. The single-file variant lives in ``DivineClient.onefile.spec`` for people
who insist on one .exe - read the warning at the top of that file first.

Ship the folder as a zip, not a loose .exe. An exe pulled out of a browser download
and double-clicked from Downloads is the scenario SmartScreen is tuned for.
"""
import os
import re
import sys

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

APP_NAME = "DivineClient"
PROJECT_ROOT = os.path.abspath(os.path.dirname(SPEC))
ICON = os.path.join(PROJECT_ROOT, "assets", "icon.ico")


def _app_version():
    """Read ``__version__`` straight out of the package - one source of truth."""
    init = os.path.join(PROJECT_ROOT, "arenclient", "__init__.py")
    try:
        with open(init, "r", encoding="utf-8") as handle:
            match = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', handle.read())
        if match:
            return match.group(1).strip()
    except OSError:
        pass
    return "0.0.0"


def _numeric(version, parts=4):
    nums = [int(n) for n in re.findall(r"\d+", version or "")][:parts]
    while len(nums) < parts:
        nums.append(0)
    return tuple(nums)


def write_version_resource(version):
    """Emit the Windows version resource and return its path.

    ``EXE(version=...)`` is given a *text* file (PyInstaller's own format) rather
    than an object, because that is the form that parses identically across
    PyInstaller versions. The generated file lands in ``build/`` so it can never go
    stale: it is rewritten from ``arenclient.__version__`` on every build.
    """
    nums = _numeric(version)
    text = """# UTF-8
#
# Generated by DivineClient.spec from arenclient.__version__ - do not edit by hand,
# it is rewritten on every build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Divine Dev Team'),
            StringStruct('FileDescription', 'Divine Client - Minecraft launcher'),
            StringStruct('FileVersion', '{version}'),
            StringStruct('InternalName', 'DivineClient'),
            StringStruct('LegalCopyright', 'Copyright (C) Divine Dev Team'),
            StringStruct('OriginalFilename', 'DivineClient.exe'),
            StringStruct('ProductName', 'Divine Client'),
            StringStruct('ProductVersion', '{version}'),
            StringStruct('Comments', 'Open-source Minecraft launcher. https://divineclient.wispbyte.org')
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [0, 1200])])
  ]
)
""".format(nums=nums, version=version)
    out_dir = os.path.join(PROJECT_ROOT, "build")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "version_info.txt")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return path


VERSION = _app_version()
VERSION_FILE = write_version_resource(VERSION)

# Ship only what a code path actually loads. "assets/_original_ai_logo" is a design drop
# (2.7 MB) that nothing reads, and a smaller _internal is quicker for an on-access scanner
# to walk - every MB of a fresh hash is reputation we do not have. Everything else below is
# read by name at runtime: the logo and emblem, the four UI marks, the mono window icon,
# the Home banner art, and the jar of the in-game companion mod.
#
# A test (tests/test_ui_shell.py) greps every "assets/..." string the UI asks for and fails
# if any of it is missing here, because a missing asset in a built exe is silent: the code
# falls back to text and the icons are simply gone for players while they look fine to us.
# The marks are globbed below for the same reason: a hand-maintained list is how an icon
# added to assets/ quietly stopped shipping.
ASSET_FILES = ("emblem.png", "logo.png", "logo_stacked.png", "icon.ico",
               "icon.png", "divine_icon.png", "divine_badge.png",
               "minecraft_tree_shaders.png", "hero_bg.png",
               "bg_beach_sunset.png", "bg_city_skyline.png",
               "bg_snowy_mountains.png", "ready_room_bg.png")
_ASSETS_DIR = os.path.join(PROJECT_ROOT, "assets")
if os.path.isdir(_ASSETS_DIR):
    ASSET_FILES += tuple(sorted(n for n in os.listdir(_ASSETS_DIR)
                                if n.startswith(("ui_", "icon_mono", "loader_", "bg_"))))
datas = [(os.path.join(PROJECT_ROOT, "assets", name), "assets")
         for name in ASSET_FILES
         if os.path.isfile(os.path.join(PROJECT_ROOT, "assets", name))]
datas += collect_data_files("customtkinter")
web_dir = os.path.join(PROJECT_ROOT, "arenclient", "web")
if os.path.isdir(web_dir):
    datas.append((web_dir, "arenclient/web"))

hiddenimports = ["PIL._tkinter_finder"]
hiddenimports += collect_submodules("minecraft_launcher_lib")
hiddenimports += collect_submodules("customtkinter")
hiddenimports += collect_submodules("pypresence")
hiddenimports += collect_submodules("arenclient")
hiddenimports += collect_submodules("flask")
hiddenimports += collect_submodules("webview")

# Not used by the launcher, and every one of these drags another pile of DLLs into
# _internal (bigger download, more files for an on-access scanner to chew on). If a
# plugin ever needs one, delete it from this list rather than from the codebase.
excludes = [
    "numpy", "scipy", "pandas", "matplotlib",
    "PyQt5", "PyQt6", "PySide2", "PySide6",
    "IPython", "pytest", "test", "setuptools",
]

a = Analysis(
    [os.path.join(PROJECT_ROOT, "main.py")],
    pathex=[PROJECT_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,           # <- onedir: files sit in _internal, not in the exe
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                       # never pack the bootloader; UPX == detection
    upx_exclude=[],
    runtime_tmpdir=None,             # onedir never extracts anything at runtime
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON if os.path.isfile(ICON) else None,
    version=VERSION_FILE,            # PyInstaller's EXE kwarg is `version`, not
    uac_admin=False,                 # `version_info` - and an unknown kwarg is
    uac_uiaccess=False,              # silently ignored. No elevation prompt.
    contents_directory="_internal",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=APP_NAME,
)
